unstable_features = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"
reorder_impl_items = true
blank_lines_upper_bound = 1
tab_spaces = 2
max_width = 100
use_small_heuristics = "Max"
chain_width = 100
overflow_delimited_expr = true
struct_field_align_threshold = 20
enum_discrim_align_threshold = 20
use_field_init_shorthand = true
match_arm_blocks = false